# Configuration file in YAML format
# https://en.wikipedia.org/wiki/YAML#Basic_components

# specify your NHL.TV account email
# emailNhltv: johndoe@gmail.com
emailNhltv:
# and password
# passwordNhltv: johnDoesNhlTvPassword
passwordNhltv:

# this timezone is used to determine `today`, point in time from where to start
# showing matches; should probably leave this as is
# if set to like, Tokyo, you will always see tomorrow's matches
matchTimeZone: America/Denver

# do not jump into the middle of a game, always start from beginning
# does not have effect if there are previous files downloaded - will continue
# downloading from where it ended
playLiveGamesFromStart: true

# set your favourite teams, will highlight them in the list
# get abbreviations from
# https://statsapi.web.nhl.com/api/v1/teams
# favouriteTeams: [WSH, PIT, TBL]
favouriteTeams: []

# add extra options to streamlink
# e. g. if you have a fast connection you can significantly reduce download
# times by using more than 1 threads
# streamlinkExtraOptions: [--hls-segment-threads, 2]
streamlinkExtraOptions: []

# do not show other teams' games in case favorite teams are set
hideOtherTeams: false

# strategy to select preferred feed
# the default strategy means that it will prefer the feed for a favorite team
#   and it will give up if it finds multiple feeds
# the 'fallbackToAny' strategy will act like the default strategy,
#   but if there are multiple preferred feeds then it picks the first one
#preferredFeedStrategy: fallbackToAny

# preferred stream quality
# currently NHLTV offers 216p, 288p, 360p, 504p, 540p, 720p, 720p60
# 'best' and 'worst' are also available
#preferredStreamQuality: best

# preferred provider
# 'nhltv' or 'espn'
# preferredProvider: nhltv

# when false, will only show feeds from preferredProvider.
showOtherProviders: false

# whether to use legacy NHL.TV API to get the game status
disableLegacyNhltvGameStatus: false


# ===================================
# everything below is NOT working yet
# ===================================

# this can be used for automatic cron job download once a day
# will select preferred feed for favourite team
# or first available if the only found game does not include one of
# `favouriteTeams`
startDownloadingIfSingleGameFound: true

# specify viaplay country code
#viaplayCountry: se
