services:
  nhltv:
    container_name: "nhltv"
    stdin_open: true
    tty: true
    build: .
    working_dir: /app
    env_file:
      - .env
    volumes:
      # map the config and src to avoid always having to rebuild the container after changes
      - ./config.yaml:/app/config.yaml
      - ./src:/app/src
      # logs, session data
      - ./tmp:/app/tmp
      # downloads
      - ${DOWNLOAD_DIR}:/app/video
      # uncomment when modifying dependencies
      #- ./package.json:/app/package.json
      #- ./yarn.lock:/app/yarn.lock
